[package]
name = "global_ssh_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.22.1"
once_cell = "1.16.0"
txt_writer = "0.1.4"
encrypted_id = "0.1.5"
